trigger:
- main

pool: mera-agent-pool

steps:
- task: SonarQubePrepare@5
  displayName: SonarQubePrepare
  inputs:
    SonarQube: 'mera-todo-sonar'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'TodoApp'
    cliProjectName: 'TodoApp'
    cliSources: '.'

- task: SonarQubeAnalyze@5
  displayName: SonarQubeAnalyze

- task: SonarQubePublish@5
  displayName: SonarQubePublish
  inputs:
    pollingTimeoutSec: '300'
