trigger:
- main

pr: none

pool:
  name: mera-agent-pool

steps:
- checkout: self

- task: SonarQubePrepare@5
  displayName: Prepare SonarQube Analysis
  inputs:
    SonarQube: 'mera-todo-sonar'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: 'TodoApp'
    cliProjectName: 'TodoApp'
    cliSources: '.'

- script: |
    npm install
    npm run build
  displayName: Build

- task: SonarQubeAnalyze@5
  displayName: Run SonarQube Analysis

- task: SonarQubePublish@5
  displayName: Publish Quality Gate
  inputs:
    pollingTimeoutSec: '300'
