sonar.projectKey=terraform-local-project
sonar.projectName=Terraform Local Scan
sonar.projectVersion=1.0

sonar.sources=.
sonar.language=terraform

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=squ_6bc8ca9e798ac11f69bb5d774c8da7ce29935e73


# Terraform specific
sonar.iac.terraform.version=1.5
sonar.exclusions=.terraform/**,**/.terraform/**,**/*.tfstate
